version: "3.3"

services:
  dnsmasq:
    container_name: inethi-dnsmasq
    restart: always
    image: jpillora/dnsmasq:latest
    ports:
      - 53:53/udp
      - "5380:8080"
    volumes:
      - "${DNSMASQ_VOLUME}/dnsmasq.conf:/etc/dnsmasq.conf:ro"
  traefik:
    image: traefik:v2.4
    container_name: inethi-traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_API_RULE}`)"
      - "traefik.http.routers.api.service=${TRAEFIK_API_SERVICE}"
      - "traefik.http.routers.api.entrypoints=${TRAEFIK_API_ENTRYPOINT}"
    depends_on:
      - dnsmasq

networks:
  default:
    external:
      name: ${INETHI_NETWORK}
