FROM nginx:latest

    # Sets up Nginx with php-fpm and required php plugins
    RUN apt-get update && apt-get upgrade -y
    RUN apt-get -y install php-fpm php-cli php-mysql php-gd php-curl php-xml php-mbstring php-intl 
    RUN apt-get -y install  git wget

    # Locales
    RUN apt-get install -y locales locales-all
    ENV LC_ALL en_US.UTF-8
    ENV LANG en_US.UTF-8
    ENV LANGUAGE en_US.UTF-8
    
    ## Install the RADIUSdesk RDCore based on CakePHP v3 Application

    # Copy the RdCore setup script to the image
    # This will create an rdcore directory containing some sub-folders.
    COPY ./setup_radius.sh /



