
FROM jtreminio/php:7.4
    # Sets up Nginx with php-fpm and required php plugins
    #RUN apt-get update && apt-get upgrade -y
    RUN apt-get update
    #ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
    #RUN chmod +x /usr/local/bin/install-php-extensions

    # mbsintr xml curl installed by default (mysqli replaced mysql)
    # cli missing
    #RUN install-php-extensions  mysqli gd intl
    
    #RUN apt-get install -y zlib1g-dev libicu-dev libpng-dev libcurl4-gnutls-dev libxml2-dev g++
    #RUN apt-get -y install  php-cli php-mysql php-gd php-curl php-xml php-mbstring php-intl 
    
    #RUN docker-php-ext-install  mysqli gd && \
    #  docker-php-ext-configure intl && \
    #  docker-php-ext-install intl
    #RUN docker-php-ext-install mysqli gd curl xml mbstring pdo_mysql && \
    