version: '2'
services:
  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_db_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sqladmin
    ports:
      - "8080:80"
    links:
      - mysql:db
    restart: always

  encoder:
    image: ronaldod/avideo-encoder
    container_name: encoder
    environment:
      SITE_TITLE: I_love_videos
      DOMAIN: fqdn_of_the_server
      DOMAIN_PROTOCOL: http
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: your_email
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_db_password
      LANG: en
    ports:
      - "8000:80"
      - "8443:443"
    links:
      - mysql:db
    restart: always
  
  youphptube:
    image: ronaldod/avideo
    container_name: avideo
    environment:
      SITE_TITLE: I_love_videos
      DOMAIN: fqdn_of_the_server
      DOMAIN_PROTOCOL: http
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: your_email
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_db_password
      LANG: en
      Encoder_Port: 8000
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql:db
    restart: always
